name: Get Changed Folders

on: 
  push: 
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  get_changed_folders: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Get changed files
      #   run: |
      #     changed_files=$(git diff-tree --no-commit --name-only -r ${{ github.event.head_commit.id }})
      #     # echo "::set-output name=changed_files::$changed_files"
      #     echo "changed_files=$changed_files" >> $GITHUB_OUTPUT

      - name: Find directories with kcl.mod and src
        run: | 
          # Find directories containing kcl.mod and src folder
          dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | awk -F'/' '{print $1}' | sort -u | uniq)
          tree .
          matching_dirs=()
          for dir in $(echo "$dirs" | tr '\n' ' '); do
            echo "Checking $dir"
            set +e
            if [ -f "$dir/kcl.mod" ] && [ -d "$dir/src" ]; then
              echo "Found $dir"
              matching_dirs+=("$dir")
            fi
            set -e
          done
          echo "Matched directories: ${matching_dirs[@]}"
          echo "dirs=$matching_dirs" >> $GITHUB_OUTPUT
